

platforms:
  teensy41:
    board: teensy:teensy:teensy41
    package: teensy:teensy
    gcc:
      features:
      defines:
        - ARDUINO_TEENSY41
      warnings:
      flags:

packages:
  teensy:teensy:
    url: https://www.pjrc.com/teensy/package_teensy_index.json


compile:
  # Choosing to run compilation tests on 2 different Arduino platforms
  platforms:
    - uno
    # - due
    # - zero
    # - leonardo
    - m4
    - esp32
    - esp8266
    # - mega2560
    # - rpipico
    - teensy41

