name: DOXYGEN

on: [push, pull_request]
jobs:
  doxygen:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: |
          ls -al
          pwd
          ls -al ..
          ls -al ..
      - uses: actions/checkout@v4
      - uses: mattnotmitt/doxygen-action@v1.9.8
        with:
          working-directory: '..'
          doxyfile-path: 'doxyfile'

