name: DOXYGEN

on: [push, pull_request]
jobs:
  doxygen:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - run: |
          ls -al
      - uses: mattnotmitt/doxygen-action@v1.9.8
        with:
          working-directory: '.'
          doxyfile-path: 'doxyfile'

