name: DOXYGEN

on: [push, pull_request]
jobs:
  doxygen:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: mattnotmitt/doxygen-action@v1.9.8
        with:
          doxyfile-path: './'
          
