
name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    #  added timeout
    timeout-minutes: 20
    strategy:
      matrix:
        example: [examples/A1301_demo.ino]
  
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
  
      - name: Build PlatformIO examples
        run: pio ci --board=uno
        env:
          PLATFORMIO_CI_SRC: ${{ matrix.example }}